### PR TITLE
Rep client auth page

### LINKED ISSUE #23: Authentication page
Create an authentication page that stores the returned JWT token.

### LINKED ISSUE #32: Prevent unauthorized access
Ensure that anyone who uses the app is authorised.

This will be done via a Guard.

Child of #23

### LINKED ISSUE #36: From handling for Authentication page
Ensure form is handled with appropriate error messages.
Child of #23

### LINKED ISSUE #37: Handle successful auth form submition
When a user logs in successfully  should be redirected to home.
Child of #23

### LINKED ISSUE #38: Create appropriate state and action for successful authentication
An action to indicate the user has attempted to log in and has successfully done so, along side with any loading indication.
Child of #37

### PR DESCRIPTION
**Pull request by HarryPi**
## New Features
- Auth Page created
- Checks for inputs
- Store for auth page
- Test for all features

## Bugs introduced
- None

## Issues / Bugs to be closed

Closes #36, closes #37, closes #38, closes #32, closes #23

### CODE REVIEW

**Comment by markscamilleri** [comment]
`.idea` folder and files should not be committed. You can leave it for now as I'll remove them from the repo with the linter fix.

**Comment by markscamilleri** [comment]
So, we're using the `indigo-pink` theme? Or is this for now till we add customizing? (It's important to unify the look and feel (and make it different enough so one can tell it's the RepClient or AdminClient)

**Comment by HarryPi** [comment]
No not necessarily if u remember we said we will decide on that on Phase 2. The good think with Angular is how easily we can switch that theme so there is no reason to agree to it now

**Comment by markscamilleri** [comment]
> No not necessarily if u remember we said we will decide on that on Phase 2. The good think with Angular is how easily we can switch that theme so there is no reason to agree to it now

Ok, cool 😃

**Pull request merged**
